// <auto-generated />
namespace Icatu.EmployeeManagerAPI.WebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class correct_department_size : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(correct_department_size));
        
        string IMigrationMetadata.Id
        {
            get { return "202001170214338_correct_department_size"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
